name: Build Plugins

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.Modules.LogiStats
          path: src/Artemis.Plugins.Modules.LogiStats/bin/x64/Release/net8.0/publish
